### ISSUE TITLE
[Logbook] - Logbook detail page

### ISSUE THREAD

**Issue by devformatters** [thematters/traveloggers-app#146]
Components:
* Log List
* Log List Item
  * OpenSea link
  * EtherScan Link

Note:
* Layout & backgrounds should be reused with [list page](https://github.com/orgs/thematters/projects/3#card-72580487)

**Comment by tx0c** [comment]
https://github.com/thematters/traveloggers-app/pull/159#issuecomment-969776323 was closing the wrong one; re-opened
