### ISSUE TITLE
[Traveloggers] App need a Cloudfront function to handle dynamic paths 404 redirect problem

### ISSUE THREAD

**Issue by tx0c** [thematters/traveloggers-app#239]
all dynamic paths `/owner/[address]` `/logbooks/[entry]` still suffers the problem; a cloudfont function should be able overwrite the 404 status code (from S3 origin)

**Comment by robertu7** [comment]
I think it's fixed by updating S3 setting `Error document - optional`.



![Image](https://user-images.githubusercontent.com/4065233/188595640-a7b0317f-4a72-4675-a71d-1dac5e40177f.png)
