### ISSUE TITLE
[Traveloggers] - Revise my logbook entry

### ISSUE THREAD

**Issue by devformatters** [thematters/traveloggers-app#251]
Since Travloggers is an entry point to both 1.0, 2.0 and claim, need to revise `my logbook` button. Check [design](https://www.figma.com/file/Ffj9jWOJ8ag4wvApRD0HwZ/Logbook-2.0?node-id=330%3A1050).

**Comment by robertu7** [comment]
@devformatters has already made related changes on #262 , guess we can close this issue.
